version: "3.8"

services:
  app:
    build: .
    restart: on-failure
    container_name: "app_backend_c"
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY = ${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY = ${AWS_SECRET_KEY}
      - OPEN_AI_KEY = ${OPEN_AI_KEY}